name: Tesis VR CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: self-hosted  # Usa tu CachyOS
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build StandaloneWindows64
        run: |
          # Ruta exacta encontrada en tu CachyOS
          /home/mauros/Unity/Hub/Editor/6000.3.12f1/Editor/Unity \
            -batchmode \
            -nographics \
            -silent-crashes \
            -quit \
            -projectPath . \
            -buildWindows64Player "build/SeriousGame.exe" \
            -logFile /dev/stdout

      - name: Subir Artefacto (.exe)
        uses: actions/upload-artifact@v4
        with:
          name: SeriousGame-Build-Windows
          path: build/
